channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - parallel=20210222
  - r-argparser=0.6
  - r-automap=1.0_14
  - r-base=3.5.1
  - r-codetools=0.2_16
  - r-dplyr=0.8.5
  - r-ggplot2=3.3.0
  - r-ggrepel=0.8.2
  - r-httpuv=1.5.2
  - r-mapdata=2.3.0
  - r-maps=3.3.0
  - r-maptools=0.9_9
  - r-raster=3.1_5
  - r-readr=1.3.1
  - r-rgdal=1.4_8
  - r-sp=1.4_1
  - r-spacetime=1.2_3
  - r-viridis=0.5.1
  - r-viridislite=0.3.0
